server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
